### ISSUE TITLE
cannot unmarshal string into Go struct

### ISSUE THREAD

**Issue by udAL** [sethvargo/gcr-cleaner#10]
Hi,
I'm sending payload:
`{"repo":"gcr.io/project/repo","grace":"24h"}`
And I'm getting:
`failed to decode payload as JSON: json: cannot unmarshal string into Go struct field Payload.grace of type time.Duration`
But if I send an integer grace it works as it should.

I don't know golang, but to the best of my knowledge, I think the issue it's you created function UnmarshalJSON to handle different Grace formats (and calling time.ParseDuration) but you never called UnmarshalJSON. Related to GH-7 issue

Anyway, just letting you know. Thanks for the tool

**Comment by sethvargo** [comment]
Can you make sure you have the most recent version? This has been fixed in a recent release.

**Comment by udAL** [comment]
Looking at `gcr.io/gcr-cleaner/gcr-cleaner` looks like the latest tag it's on an older revision
![image](https://user-images.githubusercontent.com/6889962/77626533-cebada00-6f45-11ea-968e-b2b208d1e43d.png)
I just tried tab 0.2.0 with a string grace and it works fine. Shouldn't the latest tag be on the last revision? Otherwise it would be good to specify 0.2.0 tag on your instructions

**Comment by sethvargo** [comment]
Hmm 0.2.0 should not be up there. We don't mirror the git tags. The most recent push is up there now.
