### ISSUE TITLE
Support ignore tag flag

### ISSUE THREAD

**Issue by mavrick** [sethvargo/gcr-cleaner#11]
Awesome utility! Thank you very much.

I went and setup about 20 different jobs with the `grace` and the `allow_tagged` flags enabled, and it just ended up deleting everything 😅

So, would it be possible for both  `grace` and `allow_tagged` to work together, or: an `ignore_tag` flag so, the latest tagged image isn't deleted.

Cheers

**Comment by sethvargo** [comment]
Hi @mavrick 

Can you tell me a bit more about your setup? What values did you use for `grace` and `allow_tagged`?

**Comment by ibrunotome** [comment]
@sethvargo This happened with me too, `grace: 720h` and `allow_tagged: true` and it deleted everything 😅

**Comment by mavrick** [comment]
i tag the images with a `SHORT_SHA`. apart of my cloudbuild script is to update the deployment image in my kubernetes cluster.

```kubectl set image deployment my-service my-container=gcr.io/textures-1204/my-service:$SHORT_SHA```

so all my images in the container registery contain a tag, even the latest image.

```gcloud scheduler jobs create http "gcrclean"   --project ${PROJECT_ID}   --description "Cleanup ${REPO}"   --uri "${SERVICE_URL}/http"   --message-body "{\"repo\":\"${REPO}\",\"grace\":\"720h\",\"allow_tagged\":true}"   --oidc-service-account-email "gcr-cleaner-invoker@${PROJECT_ID}.iam.gserviceaccount.com"   --schedule "every monday 09:00" ```
