### ISSUE TITLE
Exempt most recent ref image from cleanup?

### ISSUE THREAD

**Issue by StevenACoffman** [sethvargo/gcr-cleaner#12]
What do you think about a flag to exempt the most recent image from cleanup?

We find that with some of our images, the cadence of updates varies, especially over long holidays 😏.

**Comment by sethvargo** [comment]
As long as the image is tagged, it shouldn't be cleaned up. Wouldn't the latest image be tagged `latest`?

**Comment by StevenACoffman** [comment]
Sorry, my bad. I meant for use in conjunction with the "allow_tagged" flag.

**Comment by sethvargo** [comment]
Ah yea, that'd probably be a good enhancement. Do you want to take a stab at a PR?

**Comment by StevenACoffman** [comment]
Oh, I forgot about this! I will try to make time for a PR

**Comment by Sytten** [comment]
Also need this!

**Comment by sethvargo** [comment]
Fixed in #13 - Thanks @sy

**Comment by StevenACoffman** [comment]
Thanks @Sytten ! Sorry I had trouble digging out in time to do it myself!

**Comment by sethvargo** [comment]
I just released a new version.
