### ISSUE TITLE
Support running inside a Kubernetes CronJob

### ISSUE THREAD

**Issue by Sytten** [sethvargo/gcr-cleaner#14]
I think it would be valuable to create another entrypoint to directly run the cleaner with the specified parameters so it is possible to run inside GKE directly.

**Comment by sethvargo** [comment]
Do you have an example?

**Comment by Sytten** [comment]
I mean, basically it would be a docker image that launches the cleaner with something like:
`./gcp-cleaner --repo gcr.io/repo/test --allow-tagged`

**Comment by sethvargo** [comment]
I guess I'm confused? Is there a reason the existing image at `gcr.io/gcr-cleaner/gcr-cleaner` doesn't work for this use case?

**Comment by Sytten** [comment]
The current image is running a web server and waits for a request right?
Inside a CronJob you would directly execute the cleaning. Otherwise you need to keep a pod alive and do CronJob to ping it.

**Comment by sethvargo** [comment]
Ah I see. So you basically want two different binaries:

- `gcrcleaner-server` - gets requests and runs the cleaner
- `gcrcleaner-runner` - CLI that is invoked with flags and exists when done

Is that correct?

**Comment by Sytten** [comment]
Exactly! 
It would be nice to have a docker image for each too.  And the second (`gcrcleaner-runner`) could allow an override of CMD parameters so the k8s deployment can specify the flags.

**Comment by sethvargo** [comment]
I think I'll likely update the existing binary to support to commands `server` and `run` with appropriate flags.
