### ISSUE TITLE
Delete purely on age rather than checking if it is untagged

### ISSUE THREAD

**Issue by jtmiclat** [sethvargo/gcr-cleaner#2]
Thanks for creating this! I've been looking for a solution for the image lifecycle for GCR for a while

For my use case, I build and tag images based on git commit hash so all images built will forever have a tag. It would be nice to allow an option that purely checks age when deleting an image for this use case

I can implement this if ever it seems like a good idea!

**Comment by sethvargo** [comment]
There's already a date check, so you just need to add a configurable to override tags: https://github.com/sethvargo/gcr-cleaner/blob/50014ab94ba8cdc29c28b95e52dc91c132b63439/pkg/gcrcleaner/cleaner.go#L136

**Comment by steren** [comment]
+1 to the suggestion of being able to ignore tags.

This is very relevant to teams who are tagging their images with e.g. the git commit sha

**Comment by sethvargo** [comment]
Hey @steren it already ignores all tagged images. This request is asking to specifically allow deleting tagged images iff they are older than a date (if I understand correctly)

**Comment by steren** [comment]
Of course it does. Sorry if ore my comment about tags.

In my use of gcr-cleaner, I would actually prefer a time-based garbage collection than a tag base one:

Even if my images have tags, I'd like to delete them if they are older than N days.

**Comment by jtmiclat** [comment]
I tried working on this but I am facing an issue. I cannot seem to delete images that are still tagged.

I am getting this error when trying to delete an image that is still tagged.
```
 {\"errors\":[{\"code\":\"GOOGLE_MANIFEST_DANGLING_TAG\",\"message\":\"Manifest is still referenced by tag: latest\"}
```
Branch I am working: https://github.com/jtmiclat/gcr-cleaner/tree/add-tagged-param 

Any suggestions on how to address this? I tried looking at https://godoc.org/github.com/google/go-containerregistry/pkg/v1/remote#Delete but there isn't any info on how to address this.

**Comment by sethvargo** [comment]
If I recall correctly, you'll actually need to untag them first (delete the tags) . I can work on this in a few days.

**Comment by sethvargo** [comment]
From https://raw.githubusercontent.com/google/go-containerregistry/e0f538712eb0767ae6959531febe6041fa466602/cmd/gcrane/README.md

```<!--
TODO: implement this.

## untag

The [registry api](https://docs.docker.com/registry/spec/api/#deleting-an-image)
only allows deleting images by digest:

> For deletes, reference must be a digest or the delete will fail.

gcr.io allows deleting a manifest with a *tag* reference, which it
interprets as a request to untag the image, not delete it. This leaves the
image intact but still pullable by digest (or any other tags).
-->```

So it looks like gcr doesn't actually support the Untag API, which means we can't actually delete tags. @steren @jtmiclat 

Weirdly, it's possible via the UI though.

**Comment by jtmiclat** [comment]
@sethvargo I looked at how the CLI `gcloud container images delete` implements the untag functionality and figured out it is the same API as deleting an image but instead of sending the image name as  `<image>@<ref>`, you pass in `<image>:<tag>`.

**Comment by sethvargo** [comment]
:doh:

**Comment by steren** [comment]
Thanks!

This was indeed what I understood from the quoted text in https://github.com/sethvargo/gcr-cleaner/issues/2#issuecomment-580501545
