### ISSUE TITLE
Question: why do you need to create an app engine for running cloud scheduler ?

### ISSUE THREAD

**Issue by tigerwill90** [sethvargo/gcr-cleaner#22]
First of all thanks for this great project !

I wonder why it is necessary to create an app engine to run a cloud scheduler job ? 
In reference to this command :
````
gcloud app create \
  --project "${PROJECT_ID}" \
  --region "us-central" \
  --quiet
````

**Comment by sethvargo** [comment]
That's a Cloud Scheduler (and Cloud Tasks) requirement. /shrug I don't have more information on _why_ though.

**Comment by tigerwill90** [comment]
I have deactivate app engine and it's still working fine, hence my question. I see that it's also possible to run cron task from App Engine but I think it's a different service from Cloud Scheduler.

**Comment by sethvargo** [comment]
I'm not sure, you can see the note here: https://cloud.google.com/scheduler/docs#supported_regions

**Comment by tigerwill90** [comment]
Ok indeed, I have created a Cloud Scheduler in a fresh project and it automatically creates an app engine. Thank's for your time.
