### ISSUE TITLE
Unclear about CLI auth

### ISSUE THREAD

**Issue by darkvertex** [sethvargo/gcr-cleaner#33]
So I see from the README this exists `docker run -it us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli`
but the auth it takes is a `-token` flag.

How would I get a valid token for my generated service account?

**Comment by sethvargo** [comment]
https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials

**Comment by yspreen** [comment]
That's not really an answer. The default case for gcloud authentication is a key json file. It's really hard to find out how you would turn that into a simple token for gcr cleaner. If the docs for this repo don't include a minimum working example, why does the CLI even exist? What's the use case you envision for the CLI?

**Comment by sethvargo** [comment]
> The default case for gcloud authentication is a key json file.

That's inaccurate. There are many ways to authenticate via gcloud, including via user credentials (e.g. `gcloud auth login`) through a browser flow.

> It's really hard to find out how you would turn that into a simple token for gcr cleaner.

There are 4 examples of valid token types on the page I linked. If you're already authenticated to gcloud, you could run:

```
gcloud auth print-access-token
```

If you're running on a VM or VM-like workload in GCP, you can [query the metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata) for an access token or ID token.

> If the docs for this repo don't include a minimum working example, why does the CLI even exist?

While I understand you may be frustrated, your attitude is completely unwarranted.

**Comment by yspreen** [comment]
@darkvertex if you're still looking, simply running the gcloud sdk container from google might also do the trick. [Here](https://gist.github.com/yspreen/fe6bfd7eabeffe82a84f71616ab0cffe)'s an example.

**Comment by edmund-huber** [comment]
I agree that the example given in the docs is insufficient. If there's at least one known way that will always work, why not update the docs to reflect that?

**Comment by t-gebauer** [comment]
To answer the original question, if you have a service account key file, you can simply set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. No `gcloud` login, or token query steps needed.

```sh
mkdir tmp
echo "$GCP_CRED_JSON" > tmp/gcp-cred.json
docker run \
  -v "$(pwd)/tmp/:/tmp/" \
  -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-cred.json \
  us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli -repo ...
```
Where `$GCP_CRED_JSON` contains the service account JSON key.
