### ISSUE TITLE
is there a way to match everything except a constant string?

### ISSUE THREAD

**Issue by austonpramodh** [sethvargo/gcr-cleaner#49]
I am trying to use the following regex and it doesn't seem to work.

```"^(?\!(production|stage)$).*"```

I did some digging and found on StackOverflow that Golang has intentionally left this feature due to performance.

can we use [regexp2](https://github.com/dlclark/regexp2)?

[StackOverflow reference](https://stackoverflow.com/questions/42515407/is-there-a-way-to-match-everything-except-a-constant-string-using-go-regexp)

**Comment by sethvargo** [comment]
Closing due to lack of response. Thanks!

**Comment by austonpramodh** [comment]
Oh no, sorry I missed this out somehow.

So the thing I am trying to achieve is, delete all the images in gcr leaving the tags that match the regex. For example, delete all tags older than 10 days other than "production" and "stage".

**Comment by svengt** [comment]
I'm also interested in this feature. Looking for a way to delete all tagged images that are not matching a certain regex.

**Comment by svengt** [comment]
@sethvargo @austonpramodh I opened a pull request with a possible solution. This adds the possibility to inverse the filtering of tags.

**Comment by austonpramodh** [comment]
@svengt Awesome, I will take a look. All though I don't have a lot of knowledge of golang. 

I had some knowledge of Python, so I have added this functionality to a python project I found. Here it is https://github.com/austonpramodh/prune-gcr

Here is the docker image -> https://hub.docker.com/repository/docker/austonpramodh/prune-gcr

Just a beta for now.

**Comment by svengt** [comment]
@austonpramodh Nice! Thx for the tip.
