### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by WLun001** [sethvargo/gcr-cleaner#5]
How to run it locally? 

I tried `go run .` and on postman
```json
{
	"repo": "gcr.io/PROEJCT_ID/IMAGE"
}
```
I tried and it return me this error

```json
{
  "error":"failed to clean: failed to list tags for repo gcr.io/PROJECT_ID/IMAGE: Get https://gcr.io/v2/token?scope=repository%3APROJECT_ID%2FfIMAGE%3Apull\u0026service=gcr.io: failed to read metadata: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token: dial tcp 169.254.169.254:80: i/o timeout"
}
```

**Comment by sethvargo** [comment]
It's intentionally undocumented because it's not designed to be run locally. However, you can get an oauth2 access token (`gcloud auth print-access-token`) and set the `GCRCLEANER_TOKEN` environment variable.

```
GCRCLEANER_TOKEN="$(gcloud auth print-access-token)" go run .
```

Note this is not a supported way to run GCR cleaner.

**Comment by WLun001** [comment]
Thanks, I just wanted trying to understand it

**Comment by WLun001** [comment]
Hi @sethvargo , it still hit the same error
